export const types = {
  FETCH_DATA_START: "FETCH_DATA",
  FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};
export default types;
