export const types = {
  FETCH_DATA_START: "FETCH_DATA",
  FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_FILTERED_PRODUCTS: "SET_FILTERED_PRODUCTS",
  SET_ITEM_TYPE: "SET_ITEM_TYPE",
  SORT_PRODUCTS: "SORT_PRODUCTS",
};
export default types;
